# Generated by Django 3.2.13 on 2022-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220518_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
